api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("register/level", views.LevelUpdateView.as_view(), name="register-level"),
    path("register/rank", views.RankUpdateView.as_view(), name="register-rank"),
    path(
        "register/check",
        views.ApexabilityCheckView.as_view(),
        name="register-apexability",
    ),
    path(
        "compat/level/register",
        views.CompatLevelUpdateView.as_view(),
        name="register-level-compat",
    ),
    path(
        "compat/rank/register",
        views.CompatRankUpdateView.as_view(),
        name="register-rank-compat",
    ),
    path("view/level", views.level, name="view-level"),
    path("view/rank", views.rank, name="view-rank"),
    # path("view/check", views.check, name="view-check"),
    path("ow2db/upload", views.OW2DBImageUpload.as_view(), name="ow2db-upload"),
    path("game/is_tracked", views.is_tracked_game, name="game-is-tracked"),
    path(
        "game/<game_name>/emoji_name", views.get_game_emoji_name, name="game-emoji-name"
    ),
    path(
        "game/reverse_game_from_emoji",
        views.reverse_game_from_emoji,
        name="reverse-game-from-emoji",
    ),
    path("game/emoji_list", views.get_game_emoji_list, name="game-emoji-list"),
]

gamewatch/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("nextpex/", include("web.urls")),
    path("api/", include("api.urls")),
    path("ow2db/", include("ow2db_web.urls")),
]

ow2db_web/urls.py
from django.urls import path

from . import views

app_name = "ow2db_web"

urlpatterns = [
    path("screenshots", views.view_screenshots, name="list-screenshots"),
    path(
        "screenshot/<int:screenshot_id>",
        views.single_screenshot,
        name="single-screenshot",
    ),
    path("players", views.view_players, name="list-players"),
    path("player/<int:player_id>", views.single_player, name="single-player"),
    path("player", views.update_player, name="update-player"),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.root, name="root"),
    path("rank", views.rank, name="rank"),
    path("level", views.level, name="level"),
    path("check", views.apexability, name="apexability"),
    path("account", views.account, name="account"),
    # path("account/register", views.register_account, name="register-account"),
    path("account/login", views.login_account, name="login-account"),
    path("account/logout", views.logout_account, name="logout-account"),
    path("account/link", views.link_account, name="link-account"),
    path("account/link-approve", views.link_approve, name="link-approve"),
    path("check/register", views.manual_check, name="manual-check"),
]

ow2db_web/models.py
from django.db import models


# Create your models here.
class Screenshot(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.FileField(upload_to="screenshots/")
    sent_by = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"<Screenshot {self.id} by {self.sent_by} at {self.created_at}>"


class OW2UserImage(models.Model):
    id = models.AutoField(primary_key=True)
    original_sc = models.ForeignKey(
        Screenshot,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    image = models.FileField(upload_to="ow2userimages/")
    histogram = models.FileField(upload_to="ow2userhisto/", blank=True, null=True)
    ow2_user = models.ForeignKey(
        "OW2UniqueUser",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        default=None,
    )


class OW2UniqueUser(models.Model):
    id = models.AutoField(primary_key=True)
    first_seen = models.DateTimeField(auto_now_add=True)
    last_seen = models.DateTimeField(auto_now_add=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    rating = models.IntegerField(blank=True, null=True)

ow2db_web/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count, OuterRef, Subquery
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.cache import cache_control
from rest_framework.decorators import api_view
from rest_framework.exceptions import APIException
from rest_framework.response import Response

from .models import OW2UniqueUser, OW2UserImage, Screenshot
from .serializers import PlayerUpdateSerializer


# Create your views here.
@login_required
def view_screenshots(request):
    scs = Screenshot.objects.only("id").order_by("-created_at").all()

    scs_p = Paginator(scs, 5)
    page_num = request.GET.get("page", 1)
    scs = scs_p.get_page(page_num)

    return render(request, "ow2db_web/list_screenshot.html", {"images": scs})


@login_required
def view_players(request):
    subquery = (
        OW2UserImage.objects.values("ow2_user_id")
        .filter(ow2_user_id=OuterRef("id"))
        .annotate(count=Count("*"))
        .values("count")
    )[:1]

    queryset = (
        OW2UniqueUser.objects.annotate(count=Subquery(subquery))
        .values(
            "id",
            "count",
            "first_seen",
            "last_seen",
            "username",
            "comment",
            "rating",
        )
        .order_by("-last_seen")
    )

    players_p = Paginator(queryset, 25)

    page_number = request.GET.get("page", 1)
    players = players_p.get_page(page_number)

    return render(request, "ow2db_web/list_players.html", {"players": players})


@login_required
@cache_control(public=True, max_age=24 * 60 * 60)
def single_screenshot(request, screenshot_id):
    sc = Screenshot.objects.get(id=screenshot_id)
    return HttpResponse(sc.image.read(), content_type="image/png")


@login_required
@cache_control(public=True, max_age=24 * 60 * 60)
def single_player(request, player_id):
    img = (
        OW2UserImage.objects.filter(ow2_user_id=player_id)
        .order_by("-original_sc__created_at")
        .first()
    )
    return HttpResponse(img.image.read(), content_type="image/png")


@login_required
@api_view(["POST"])
def update_player(request):
    ser = PlayerUpdateSerializer(data=request.data)
    if ser.is_valid():
        ser.save()
        return Response(ser.data)
    else:
        raise APIException(detail=ser.errors, code=400)

ow2db_web/templates/ow2db_web/base.html
<html>
    <head>
        <title>{% block title %}OW2DB{% endblock %}</title>
        <meta charset="UTF-8">
        {% block header %}{% endblock header %}
    </head>
    <body>
        {% block body %}{% endblock body %}
        <div class="footer">
            
        </div>
    </body>
</html>

ow2db_web/templates/ow2db_web/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'web/header.css' %}" type="text/css">
<div class="menubar">
    <p class="menu-item menu-title">OW2DB</p>
    <a class="menu-item menu-link" href="{% url 'web:apexability' %}">NextPex</a>
    <a class="menu-item menu-link" href="{% url 'ow2db_web:list-screenshots' %}">Screenshots</a>
    <a class="menu-item menu-link" href="{% url 'ow2db_web:list-players' %}">Players</a>
    <!-- <p class="menu-item menu-link"><img src="{% static 'web/img/setting.png' %}"></p> -->
</div>
<div>
    
</div>

ow2db_web/templates/ow2db_web/list_players.html
{% extends 'ow2db_web/base.html' %}

{% load static %}

{% block header %}
{% include 'ow2db_web/header.html' %}
<link rel="stylesheet" href="{% static 'ow2db_web/list_players.css' %}">
<script>
    const UPDATE_URL = "{% url 'ow2db_web:update-player' %}";
</script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
<script src="{% static 'ow2db_web/list_players.js' %}"></script>
{% endblock header %}

{% block body %}
<table class="player-table">
    <tr>
        <th>Player ID</th>
        <th>Name</th>
        <th>Username</th>
        <th>Comment</th>
        <th>Rating</th>
        <th>Count</th>
        <th>Last seen</th>
        <th>Registered at</th>
        <th>Save</th>
    </tr>
    {% for player in players %}
        <tr>
            <!-- <form> -->
            <!-- <input type="hidden" name="player_id" value="{{player.id}}"> -->
            <td>{{player.id}}</td>
            <td><img src="{% url 'ow2db_web:single-player' player.id %}" width="50%"></td>
            <td><input id="player-{{player.id}}-username-input" type="text" value="{{player.username|default_if_none:''}}"></td>
            <td><input id="player-{{player.id}}-comment-input" type="text" value="{{player.comment|default_if_none:''}}"></td>
            <td><input id="player-{{player.id}}-rating-input" type="number" min="1" max="5" value="{{player.rating}}"></td>
            <td>{{player.count}}</td>
            <td>{{player.last_seen}}</td>
            <td>{{player.first_seen}}</td>
            <!-- <td><input type="submit" value="Save" data-player-id="{{player.id}}"></td> -->
            <td><button class="save-button" data-player-id="{{player.id}}">Save</button></td>
            <!-- </form> -->
        </tr>
    {% endfor %} 
</table>

{% if players.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ players.previous_page_number }}">previous</a>
{% endif %}
<span class="current">
    Page {{ players.number }} of {{ players.paginator.num_pages }}.
</span>
{% if players.has_next %}
    <a href="?page={{ players.next_page_number }}">next</a>
    <a href="?page={{ players.paginator.num_pages }}">last &raquo;</a>
{% endif %}

{% endblock body %}

ow2db_web/templates/ow2db_web/list_screenshot.html
{% extends 'ow2db_web/base.html' %}

{% block header %}
{% include 'ow2db_web/header.html' %}
{% endblock header %}

{% block body %}
<table>
    <tr>
        <th>id</th>
        <th>image</th>
        <th>sent_by</th>
        <th>timestamp</th>
    </tr>
    {% for image in images %}
        <tr>
            <td>{{image.id}}</td>
            <td><img src="{% url 'ow2db_web:single-screenshot' image.id %}" width="20%"></td>
            <td>{{image.sent_by}}</td>
            <td>{{image.created_at}}</td>
        </tr>
    {% endfor %} 
</table>

{% if images.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ images.previous_page_number }}">previous</a>
{% endif %}
<span class="current">
    Page {{ images.number }} of {{ images.paginator.num_pages }}.
</span>
{% if images.has_next %}
    <a href="?page={{ images.next_page_number }}">next</a>
    <a href="?page={{ images.paginator.num_pages }}">last &raquo;</a>
{% endif %}

{% endblock body %}