api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("register/level", views.LevelUpdateView.as_view(), name="register-level"),
    path("register/rank", views.RankUpdateView.as_view(), name="register-rank"),
    path(
        "register/check",
        views.ApexabilityCheckView.as_view(),
        name="register-apexability",
    ),
    path(
        "compat/level/register",
        views.CompatLevelUpdateView.as_view(),
        name="register-level-compat",
    ),
    path(
        "compat/rank/register",
        views.CompatRankUpdateView.as_view(),
        name="register-rank-compat",
    ),
    path("view/level", views.level, name="view-level"),
    path("view/rank", views.rank, name="view-rank"),
    # path("view/check", views.check, name="view-check"),
    path("ow2db/upload", views.OW2DBImageUpload.as_view(), name="ow2db-upload"),
    path("game/is_tracked", views.is_tracked_game, name="game-is-tracked"),
    path(
        "game/<game_name>/emoji_name", views.get_game_emoji_name, name="game-emoji-name"
    ),
    path(
        "game/reverse_game_from_emoji",
        views.reverse_game_from_emoji,
        name="reverse-game-from-emoji",
    ),
    path("game/emoji_list", views.get_game_emoji_list, name="game-emoji-list"),
]

gamewatch/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("nextpex/", include("web.urls")),
    path("api/", include("api.urls")),
    path("ow2db/", include("ow2db_web.urls")),
]

ow2db_web/urls.py
from django.urls import path

from . import views

app_name = "ow2db_web"

urlpatterns = [
    path("screenshots", views.view_screenshots, name="list-screenshots"),
    path(
        "screenshot/<int:screenshot_id>",
        views.single_screenshot,
        name="single-screenshot",
    ),
    path("players", views.view_players, name="list-players"),
    path("player/<int:player_id>", views.single_player, name="single-player"),
    path("player", views.update_player, name="update-player"),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.root, name="root"),
    path("rank", views.rank, name="rank"),
    path("level", views.level, name="level"),
    path("check", views.apexability, name="apexability"),
    path("account", views.account, name="account"),
    # path("account/register", views.register_account, name="register-account"),
    path("account/login", views.login_account, name="login-account"),
    path("account/logout", views.logout_account, name="logout-account"),
    path("account/link", views.link_account, name="link-account"),
    path("account/link-approve", views.link_approve, name="link-approve"),
    path("check/register", views.manual_check, name="manual-check"),
]

web/templates/web/account.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'web/account.css' %}">
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="container">
    {% include 'web/account_header.html' %}

    <!-- {% if errormsg %}
    <div>
        <p>{{errormsg}}</p>
    </div>
    {% endif %} -->

    <div class="info-entry">
        {% if player_name %}
        <p class="info-label">リンクされているプレイヤー</p>
        <p>{{player_name}}</p>
        {% else %}
        <p>リンクされているプレイヤーはありません</p>
        {% endif %}
    </div>

    {% if discord_names %}
    <div class="info-entry">
        <p class="info-label">登録されているDiscordユーザー名</p>
        次のいずれかの名前をDiscordユーザー名として利用してください。
        <ul>
            {% for name in discord_names %}
            <li>{{name}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div class="info-entry">
        <p class="info-label">プレイヤーとの紐づけ</p>
        <a href="{% url 'web:link-account' %}" class="go go-primary">Go</a>
    </div>

    {% if staff %}
    <div class="info-entry">
        <p class="info-label">紐づけの承認</p>
        <a href="{% url 'web:link-approve' %}" class="go go-primary">Go</a>
    </div>
    {% endif %}

    <a href="{% url 'web:logout-account' %}" class="go go-danger">ログアウト</a>
</div>
{% endblock body %}

web/templates/web/account_header.html
<div>
    pexアカウント: {{account_name}}
</div>

web/templates/web/account_link.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'web/account.css' %}">
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="container">
    <p>プレイヤーリンクは管理者に承認された後有効になります。</p>

    <form action="{% url 'web:link-account' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <p><button type="submit" class="go go-primary">管理者にリンク要求を送る</button></p>
    </form>
</div>
{% endblock body %}

web/templates/web/account_link_approve.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'web/account.css' %}">
<link rel="stylesheet" href="{% static 'web/link_approve.css' %}">
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="container">
    {% if not pendings %}
    <p>リンク要求がありません。</p>
    {% endif %}
    {% for p in pendings %}
    <div class="entry-table">
        <p class="label user">User</p>
        <p class="value user">{{p.user.username}}</p>
        
        <p class="label player">Player</p>
        <p class="value player">{{p.player.display_name}}</p>
        <div class="entry-actions">
            <form action="{% url 'web:link-approve' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="approve" name="action">
                <input type="hidden" value="{{p.user.username}}" name="username">
                <input type="hidden" value="{{p.player.id}}" name="player_id">
                <button type="submit" class="go go-primary">承認</button>
            </form>
            <form action="{% url 'web:link-approve' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value="reject" name="action">
                <input type="hidden" value="{{p.user.username}}" name="username">
                <input type="hidden" value="{{p.player.id}}" name="player_id">
                <button type="submit"class="go go-danger">拒否</button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

web/templates/web/apexability.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'web/apexability.css' %}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/randomcolor/0.6.1/randomColor.min.js" integrity="sha512-vPeZ7JCboHcfpqSx5ZD+/jpEhS4JpXxfz9orSvAPPj0EKUVShU2tgy7XkU+oujBJKnWmu4hU7r9MMQNWPfXsYw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'web/config.js' %}" type="module"></script>
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
{{monthly_records|json_script:"monthly_records"}}
<div id="container">
    <select id="viewTypeSelector" style="display: none;">
        <option value="overview">Overview</option>
        <!-- <option value="daily">Daily</option> -->
    </select>

    <div class="swapable active" x-view="overview" id="overview">
        最新の20件のみ表示しています。
        <table class="apexability-table">
            <thead class="table-header">
                <tr class="header-row">
                    <th class="header-cell">Name</th>
                    <th class="header-cell">Game</th>
                    <th class="header-cell">Time</th>
                    <th class="header-cell">Duration</th>
                </tr>
            </thead>
            <tbody> 
            {% for record in recent_records %}
                <tr>
                    <td>{{record.player.display_name}}</td>
                    <td>{{record.played_game.name}}</td>
                    <td>{{record.start_time}} ~ {{record.stop_time|default_if_none:""}}</td>
                    {% if record.stop_time %}
                    <td>{{record.stop_time|timeuntil:record.start_time}}</td>
                    {% else %}
                    <td><span class="playing-now-badge">Playing</span></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <!-- month selector -->
        <input type="month" id="monthSelector"/>
        <canvas id="monthChart"></canvas>
    </div>
</div>
<script src="{% static 'web/apexability.js' %}" type="module"></script>
{% endblock body %}

web/templates/web/base.html
<html>
    <head>
        <title>{% block title %}OneApex{% endblock %}</title>
        <meta charset="UTF-8">
        {% block header %}{% endblock header %}
    </head>
    <body>
        {% block body %}{% endblock body %}
        <div class="footer">
            <!-- <div>Icons made by <a href="https://www.flaticon.com/authors/srip" title="srip">srip</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
        </div>
    </body>
</html>

web/templates/web/createuser.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="container">
    <form action="{% url 'web:register-account' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <p><input type="submit" value="Register"></p>
    </form>
</div>
{% endblock body %}

web/templates/web/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'web/header.css' %}" type="text/css">
<div class="menubar">
    <p class="menu-item menu-title">NextPex</p>
    <a class="menu-item menu-link" href="{% url 'ow2db_web:list-players' %}">OW2DB</a>
    <a class="menu-item menu-link" href="{% url 'web:apexability' %}">プレイ履歴</a>
    <a class="menu-item menu-link" href="{% url 'web:account' %}">pexアカウント</a>
    <!-- <p class="menu-item menu-link"><img src="{% static 'web/img/setting.png' %}"></p> -->
</div>
<div>
    
</div>

web/templates/web/level.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/1.2.0/chartjs-plugin-zoom.min.js" integrity="sha512-TT0wAMqqtjXVzpc48sI0G84rBP+oTkBZPgeRYIOVRGUdwJsyS3WPipsNh///ay2LJ+onCM23tipnz6EvEy2/UA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" type="text/css" href="{% static 'web/chart.css' %}">
<script src="{% static 'web/config.js' %}" type="module"></script>
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="mainContent">
    <canvas id="chart"></canvas>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/randomcolor/0.6.1/randomColor.min.js" integrity="sha512-vPeZ7JCboHcfpqSx5ZD+/jpEhS4JpXxfz9orSvAPPj0EKUVShU2tgy7XkU+oujBJKnWmu4hU7r9MMQNWPfXsYw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'web/RGBmodifier.js' %}"></script>
<script src="{% static 'web/level.js' %}" type="module"></script>
{% endblock body %}

web/templates/web/login.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="container">
    {% if error_message %}
    <p class="error-message">{{error_message}}</p>
    {% endif %}
    <form action="{% url 'web:login-account' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <p><input type="submit" value="Login"></p>
    </form>
</div>
{% endblock body %}

web/templates/web/manual_check.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'web/account.css' %}">
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="container">
    {% include 'web/account_header.html' %}

    <p>前もってアカウントページでプレイヤーとリンクしておいてください。</p>

    <div>
        <form action="{% url 'web:manual-check' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="go go-primary">登録</button>
        </form>
    </div>
</div>
{% endblock body %}

web/templates/web/rank.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/1.2.0/chartjs-plugin-zoom.min.js" integrity="sha512-TT0wAMqqtjXVzpc48sI0G84rBP+oTkBZPgeRYIOVRGUdwJsyS3WPipsNh///ay2LJ+onCM23tipnz6EvEy2/UA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" type="text/css" href="{% static 'web/chart.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'web/rank.css' %}">
<script src="{% static 'web/config.js' %}" type="module"></script>
{% endblock header %}

{% block body %}
{% include 'web/header.html' %}
<div id="mainContent">
    <select id="rankTypeSelector">
        <option value="trio">Trio</option>
        <option value="arena">Arena</option>
    </select>
    <canvas id="chart"></canvas>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/randomcolor/0.6.1/randomColor.min.js" integrity="sha512-vPeZ7JCboHcfpqSx5ZD+/jpEhS4JpXxfz9orSvAPPj0EKUVShU2tgy7XkU+oujBJKnWmu4hU7r9MMQNWPfXsYw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'web/RGBmodifier.js' %}"></script>
<script src="{% static 'web/rank.js' %}" type="module"></script>
{% endblock body %}